# fly.toml app configuration file generated for msu-frontend on 2023-08-13T23:28:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "msu-frontend"
primary_region = "ams"

[build]
  dockerfile = "master.Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
